// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SanatGalerisiAPI.Data;

#nullable disable

namespace SanatGalerisiAPI.Data.Migrations
{
    [DbContext(typeof(TabloDbContext))]
    [Migration("20230907162705_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SanatGalerisiAPI.Data.Tablo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ResminYapilmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("RessamAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tablolar", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ResminYapilmaTarihi = new DateTime(2022, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RessamAdi = "Ressam1"
                        },
                        new
                        {
                            Id = 2,
                            ResminYapilmaTarihi = new DateTime(2021, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RessamAdi = "Ressam2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
